version: '3.9'

services:

  drupal:
    image: drupal:9
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres:14
    secrets:
      - psql_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
    volumes:
      - drupal-data:/var/lib/postgresql/data

secrets:
  psql_password:
    external: true

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
